# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
